---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAeFpu0UgKg/F/Yvc01axMhI5J3K+xcGeUTOCWijf6EJwng5aZD5S5sQwmheRY3ipJqy9pl4/uxyruroqjziA4m+N2gWkQHH0nSF3bbTISIjedwqmF1Y9rADi6r5wsJQb8SO74bWW8ErWtLto5dzmoTgyOkZme3lKhOdkj9jl3aURC5jDHiOHjzeswsT3gJGolCDW9awfuKQseeqJ2b1fFpjBiNvaUbFxZ6CHU38kDPG/Eka5Yf6m+vctlv3WWLZWr3XAbkWFd682iHrJLK65pMLOwcJAtq2Uoihbv4oHYRcv0T+gASkdErJvyaw4cHbGvEfBjmRNFECOhfOmcQEZI9SZB9nmYlm2ao5Zhob5MFX6WDTCttMU4tJC/kR1hzMaJUl5ZtPHTP+0lHSaNWYxDdr/tkJKMdKopdippcUJAlvz0UJStjHgaMpHIFMtsj2Hufy6LI6+HixIUEsZ8jKr77DZdRZkXyctUygjwfbhMaZ3KbqsmOv/VRvLNpHbINKtYn4zs2tdCPwU3jtwmInBN526SjTX0K3I1lZghWfim45e/cimKwOWCxFYuMXAhqg4wPDjYqH5IG1Hl/9gPQKw1VjG7kpJuAgxhlrjDfzPtDCyX9MUcPxV6lQL4mX6Zf3seGkawUwJfzAjnixq9zthYM2fHUiyE0tkjIIyjjYDoOPA4D3dPrT4dFdEwvZTgnrT11RR05vF63hW53
    STRIPE_API_KEY: AgAukLjpQPmXJPbEbNtRMd6/ZQmftGrTQtsColCp4/BGsGJzZRTrkXyaLSWp66/7DQdaU2qss1zFEE9wi4dMh1d1Rr8HCZpcqRIeJWS8WnLpFPwwJFzFBeFeh+6FjbzNLZd/SnrlfR5eucUOdKwWgzH8kYnNphzZhWaIiW7U/YsxWUQh0jmwd5A7FrpNRwhfMtl/nzSiqcvYRCbPJR3UZoKYwgdDS1aSiRuHDvh5bnrJ8v489D49DzZVoZKVg+GYihKqlLr7x/13jJWTICLiXAdiExfzaztp4N1+1eraNfySPTaxP9OLdy21CXDH9xkz6jcEtFt6da2jrgSRp1ePiZMErMIJy4yPAi1vZJprbE9+nfCy8uHoomoFywKpeps5Hs95162QqIkfvwkiiCPkFdPZsy7lt8Q5zJZaNnaJx8KoWUJO6ONOnkcPcVP6bZG6LWs4VuN3n5oPhCu4ngZHe1uff/6IY5El1i8S1HA10Hf9OAHy5geneQEJc2bqoKbBhoP0Dn5+qA811FEasvUTf+n3a36a2dt+7EWds95jjBgSqIgpr1P4E7g41pG2ryIrAvcb/C0XPyVAOGIDyRM2Rr1Kt2NGC5DJt1vn/CJfE6CPVEgv1A9nQJj1PDnXURT97VeqvNSoVMs6VUO+YhcMom4Nrl39E7qePkWgcJaJanpcldo7XMYt7oxotpEiaSVlVJFuhqETMbquExgwp59g/L+F4Jo=
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
