---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCbEzruEGCk3l6MBxvuP3DoWtiQcarGs9bzfQ2V1BX12anWlVMwrnMoWh5D8JMzhB5qF9T32plrkVhZOMmqp53j2HOccKBIaRCU9uxKoQyiVwlY/eDI4AEy06duwrni3J9iSDbILyUik9UNeYENYxC3m+wrOLpJcLowEvzxwrmyBUwniti25N8QRfj6xE3H04xykJ8RYUBjkVlJTSRy6sKR/mtYD4i2z1a4KGjicCQrQvCFBhCg/E8t+Gel9gf5WCDyY/pGXqxUctn3zOl/KL3FDT5k+oUdHgZ3qP0xm4DyOOCzDHlz6gzYsiITPD32K77YDIb8AMUTn+jC90BTJZBl0ncV+6NHeR6eYr53eeZ7hoZ2fS0QNgGJJPH6EtMVo2os0UZbuNxnXlIN+covbKVG5aUFUGoh/C6pX6NW2CgabEyAWPhvzLyY7Z7b2xF6waMZYpgwA0SgqwpLWfrPPx0LdADYHfbZ44Evy8wwDLNZVHQhgepuA9+MMF2mAqZYkn21792ycAaPmXF2zf3qf0k8iTicaLujAzhEKv0Yr0nm0PRVW7DV4y6csUq28lJoaro6XiN9wSmq1rrMIWzJ7OHCXUGcUDbYOazuvN2pi01SIFlWJd0tINMFZqMCz0zWXYYVpyPaD5sJCOFahc/rj5QGEvLYi784lO6djcW5OwfCLr3ikuXcdDdw+jq8sJ+VDsqJ0wWl58v2tVzbsQ==
    STRIPE_API_KEY: AgALP2kYPxusmd+h6wkYfExV9KNWhPZUMqEbHqJwnUB+P88QDaEE2BOxRVP0uYfdhETozyWDMlQ9/BLykYybeSI26wgY+9i1LmE54hBLi/8qYeb0Rj5aoPo8S3dy8KwbosQ32YqX0+AmfQBzbJuwzW3LbP1vMIdzmZ8WgUp43vFi43oBp3ogr8hXUdALclaClQ+ydPIXgxD1exAD9mVLVv8EF97+1GJTd6aUnphMDKIcsd1KQZD6Xqbu8WuHRP0dBOZc+QQXE50hBNAqDhMNLVgvOSlAzllOZR0C5wM4j0cvIvIQ3hpKzzSKxC8IomlDdw0zHAC3uJuXgaa3tu213CMD/uhhCrM+JPQgR6rmur5G6lWerqiRiT1WwFo/MEtPu2Olx406YA1k7Rkcd7ZWFxT2E+mu47tOT5fWVJed9gdYuccQyB8S9v+wpex00p9aA1tnlFcbYUwJx21IH+v3dTCJG4DpfRUigYF2VHPLUNK0Ak1gq6r9wExHBKU/N30ECrFN1OK9mZYoS+E1wATpaSugQy/apilBh1UC1f8wWTZxmWp+c9pG8bbFVh8/QTLv8/epS4ZJLBmZsyNMQ47HIAxrezVSvSbezDlSYHoM5AWEAMNxLxU6GhaMdLPdS21AVv0ZZQzWNacXwiYoBUWZwRBF6sHyLgxlXn/oQYS3Qz49tcG5QINLPI8e6leVlwNRoT2Qal//mrd3NXi5bd80CPQ3cCUbVc7oUPICWnpEdg==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
